-- CREATE USER
CREATE ROLE dalu_admin WITH
	LOGIN
	PASSWORD 'Neverforget0099**'
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	CONNECTION LIMIT 20;

-- CREATE DATABASE
CREATE DATABASE DALU_DB
WITH
OWNER = dalu_admin
ENCODING = 'UTF8'
LC_COLLATE = 'es_GT.UTF-8'
LC_CTYPE = 'es_GT.UTF-8'
TEMPLATE = template0
CONNECTION LIMIT = -1;

-- GRANT PERMISSIONS to connect to DA
GRANT CONNECT ON DATABASE DALU_DB TO dalu_admin;

-- GRANT PERMISSIONS TO SCHEMA AND TABLES

GRANT USAGE ON SCHEMA public TO dalu_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dalu_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dalu_admin;

-- GRANT PERMISSIONS FOR NEW TABLELS

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dalu_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO dalu_admin;

